[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.4"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.9.1"


[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.6.0"

[prune]
  go-tests = true
  unused-packages = true
